import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Page from "./components/PageLink";
import Footer from "./components/Footer";
import Header from "./components/Header";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PornHab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/youtubetwo.ico" />
      </Head>

        <Header />
      <main className={styles.main}>

      </main>
        <Footer />
    </div>
  )
}
